apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-azure
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-azure
  template:
    metadata:
      labels:
        app: devops-azure
    spec:
      containers:
        - name: react-app
          image: 7718966526/devops-azure:2309581
          ports:
            - containerPort: 3000
